package com.google.android.gms.internal.mlkit_common;

import androidx.camera.core.impl.utils.a;
import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;

/* compiled from: com.google.mlkit:common@@18.7.0 */
/* loaded from: classes.dex */
final class zzgh implements ObjectEncoder {
    static final zzgh zza = new zzgh();
    private static final FieldDescriptor zzb = a.c(1, FieldDescriptor.builder("systemInfo"));
    private static final FieldDescriptor zzc = a.c(2, FieldDescriptor.builder("eventName"));
    private static final FieldDescriptor zzd = a.c(37, FieldDescriptor.builder("isThickClient"));
    private static final FieldDescriptor zze = a.c(61, FieldDescriptor.builder("clientType"));
    private static final FieldDescriptor zzf = a.c(3, FieldDescriptor.builder("modelDownloadLogEvent"));
    private static final FieldDescriptor zzg = a.c(20, FieldDescriptor.builder("customModelLoadLogEvent"));
    private static final FieldDescriptor zzh = a.c(4, FieldDescriptor.builder("customModelInferenceLogEvent"));
    private static final FieldDescriptor zzi = a.c(29, FieldDescriptor.builder("customModelCreateLogEvent"));
    private static final FieldDescriptor zzj = a.c(5, FieldDescriptor.builder("onDeviceFaceDetectionLogEvent"));
    private static final FieldDescriptor zzk = a.c(59, FieldDescriptor.builder("onDeviceFaceLoadLogEvent"));
    private static final FieldDescriptor zzl = a.c(6, FieldDescriptor.builder("onDeviceTextDetectionLogEvent"));
    private static final FieldDescriptor zzm = a.c(79, FieldDescriptor.builder("onDeviceTextDetectionLoadLogEvent"));
    private static final FieldDescriptor zzn = a.c(7, FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent"));
    private static final FieldDescriptor zzo = a.c(58, FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent"));
    private static final FieldDescriptor zzp = a.c(48, FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent"));
    private static final FieldDescriptor zzq = a.c(49, FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent"));
    private static final FieldDescriptor zzr = a.c(18, FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent"));
    private static final FieldDescriptor zzs = a.c(26, FieldDescriptor.builder("onDeviceObjectCreateLogEvent"));
    private static final FieldDescriptor zzt = a.c(27, FieldDescriptor.builder("onDeviceObjectLoadLogEvent"));
    private static final FieldDescriptor zzu = a.c(28, FieldDescriptor.builder("onDeviceObjectInferenceLogEvent"));
    private static final FieldDescriptor zzv = a.c(44, FieldDescriptor.builder("onDevicePoseDetectionLogEvent"));
    private static final FieldDescriptor zzw = a.c(45, FieldDescriptor.builder("onDeviceSegmentationLogEvent"));
    private static final FieldDescriptor zzx = a.c(19, FieldDescriptor.builder("onDeviceSmartReplyLogEvent"));
    private static final FieldDescriptor zzy = a.c(21, FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent"));
    private static final FieldDescriptor zzz = a.c(22, FieldDescriptor.builder("onDeviceTranslationLogEvent"));
    private static final FieldDescriptor zzA = a.c(8, FieldDescriptor.builder("cloudFaceDetectionLogEvent"));
    private static final FieldDescriptor zzB = a.c(9, FieldDescriptor.builder("cloudCropHintDetectionLogEvent"));
    private static final FieldDescriptor zzC = a.c(10, FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent"));
    private static final FieldDescriptor zzD = a.c(11, FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent"));
    private static final FieldDescriptor zzE = a.c(12, FieldDescriptor.builder("cloudImageLabelDetectionLogEvent"));
    private static final FieldDescriptor zzF = a.c(13, FieldDescriptor.builder("cloudLandmarkDetectionLogEvent"));
    private static final FieldDescriptor zzG = a.c(14, FieldDescriptor.builder("cloudLogoDetectionLogEvent"));
    private static final FieldDescriptor zzH = a.c(15, FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent"));
    private static final FieldDescriptor zzI = a.c(16, FieldDescriptor.builder("cloudTextDetectionLogEvent"));
    private static final FieldDescriptor zzJ = a.c(17, FieldDescriptor.builder("cloudWebSearchDetectionLogEvent"));
    private static final FieldDescriptor zzK = a.c(23, FieldDescriptor.builder("automlImageLabelingCreateLogEvent"));
    private static final FieldDescriptor zzL = a.c(24, FieldDescriptor.builder("automlImageLabelingLoadLogEvent"));
    private static final FieldDescriptor zzM = a.c(25, FieldDescriptor.builder("automlImageLabelingInferenceLogEvent"));
    private static final FieldDescriptor zzN = a.c(39, FieldDescriptor.builder("isModelDownloadedLogEvent"));
    private static final FieldDescriptor zzO = a.c(40, FieldDescriptor.builder("deleteModelLogEvent"));
    private static final FieldDescriptor zzP = a.c(30, FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent"));
    private static final FieldDescriptor zzQ = a.c(31, FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent"));
    private static final FieldDescriptor zzR = a.c(32, FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent"));
    private static final FieldDescriptor zzS = a.c(33, FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent"));
    private static final FieldDescriptor zzT = a.c(34, FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent"));
    private static final FieldDescriptor zzU = a.c(35, FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent"));
    private static final FieldDescriptor zzV = a.c(36, FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent"));
    private static final FieldDescriptor zzW = a.c(46, FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent"));
    private static final FieldDescriptor zzX = a.c(47, FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent"));
    private static final FieldDescriptor zzY = a.c(69, FieldDescriptor.builder("pipelineAccelerationInferenceEvents"));
    private static final FieldDescriptor zzZ = a.c(42, FieldDescriptor.builder("remoteConfigLogEvent"));
    private static final FieldDescriptor zzaa = a.c(50, FieldDescriptor.builder("inputImageConstructionLogEvent"));
    private static final FieldDescriptor zzab = a.c(51, FieldDescriptor.builder("leakedHandleEvent"));
    private static final FieldDescriptor zzac = a.c(52, FieldDescriptor.builder("cameraSourceLogEvent"));
    private static final FieldDescriptor zzad = a.c(53, FieldDescriptor.builder("imageLabelOptionalModuleLogEvent"));
    private static final FieldDescriptor zzae = a.c(54, FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaf = a.c(60, FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzag = a.c(85, FieldDescriptor.builder("documentDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzah = a.c(86, FieldDescriptor.builder("documentCroppingOptionalModuleLogEvent"));
    private static final FieldDescriptor zzai = a.c(87, FieldDescriptor.builder("documentEnhancementOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaj = a.c(55, FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent"));
    private static final FieldDescriptor zzak = a.c(56, FieldDescriptor.builder("nlClassifierClientLibraryLogEvent"));
    private static final FieldDescriptor zzal = a.c(57, FieldDescriptor.builder("accelerationAllowlistLogEvent"));
    private static final FieldDescriptor zzam = a.c(62, FieldDescriptor.builder("toxicityDetectionCreateEvent"));
    private static final FieldDescriptor zzan = a.c(63, FieldDescriptor.builder("toxicityDetectionLoadEvent"));
    private static final FieldDescriptor zzao = a.c(64, FieldDescriptor.builder("toxicityDetectionInferenceEvent"));
    private static final FieldDescriptor zzap = a.c(65, FieldDescriptor.builder("barcodeDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaq = a.c(66, FieldDescriptor.builder("customImageLabelOptionalModuleLogEvent"));
    private static final FieldDescriptor zzar = a.c(67, FieldDescriptor.builder("codeScannerScanApiEvent"));
    private static final FieldDescriptor zzas = a.c(68, FieldDescriptor.builder("codeScannerOptionalModuleEvent"));
    private static final FieldDescriptor zzat = a.c(70, FieldDescriptor.builder("onDeviceExplicitContentCreateLogEvent"));
    private static final FieldDescriptor zzau = a.c(71, FieldDescriptor.builder("onDeviceExplicitContentLoadLogEvent"));
    private static final FieldDescriptor zzav = a.c(72, FieldDescriptor.builder("onDeviceExplicitContentInferenceLogEvent"));
    private static final FieldDescriptor zzaw = a.c(73, FieldDescriptor.builder("aggregatedOnDeviceExplicitContentLogEvent"));
    private static final FieldDescriptor zzax = a.c(74, FieldDescriptor.builder("onDeviceFaceMeshCreateLogEvent"));
    private static final FieldDescriptor zzay = a.c(75, FieldDescriptor.builder("onDeviceFaceMeshLoadLogEvent"));
    private static final FieldDescriptor zzaz = a.c(76, FieldDescriptor.builder("onDeviceFaceMeshLogEvent"));
    private static final FieldDescriptor zzaA = a.c(77, FieldDescriptor.builder("aggregatedOnDeviceFaceMeshLogEvent"));
    private static final FieldDescriptor zzaB = a.c(78, FieldDescriptor.builder("smartReplyOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaC = a.c(80, FieldDescriptor.builder("textDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaD = a.c(81, FieldDescriptor.builder("onDeviceImageQualityAnalysisCreateLogEvent"));
    private static final FieldDescriptor zzaE = a.c(82, FieldDescriptor.builder("onDeviceImageQualityAnalysisLoadLogEvent"));
    private static final FieldDescriptor zzaF = a.c(83, FieldDescriptor.builder("onDeviceImageQualityAnalysisLogEvent"));
    private static final FieldDescriptor zzaG = a.c(84, FieldDescriptor.builder("aggregatedOnDeviceImageQualityAnalysisLogEvent"));
    private static final FieldDescriptor zzaH = a.c(88, FieldDescriptor.builder("imageQualityAnalysisOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaI = a.c(89, FieldDescriptor.builder("imageCaptioningOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaJ = a.c(90, FieldDescriptor.builder("onDeviceImageCaptioningCreateLogEvent"));
    private static final FieldDescriptor zzaK = a.c(91, FieldDescriptor.builder("onDeviceImageCaptioningLoadLogEvent"));
    private static final FieldDescriptor zzaL = a.c(92, FieldDescriptor.builder("onDeviceImageCaptioningInferenceLogEvent"));
    private static final FieldDescriptor zzaM = a.c(93, FieldDescriptor.builder("aggregatedOnDeviceImageCaptioningInferenceLogEvent"));
    private static final FieldDescriptor zzaN = a.c(94, FieldDescriptor.builder("onDeviceDocumentDetectionCreateLogEvent"));
    private static final FieldDescriptor zzaO = a.c(95, FieldDescriptor.builder("onDeviceDocumentDetectionLoadLogEvent"));
    private static final FieldDescriptor zzaP = a.c(96, FieldDescriptor.builder("onDeviceDocumentDetectionLogEvent"));
    private static final FieldDescriptor zzaQ = a.c(97, FieldDescriptor.builder("aggregatedOnDeviceDocumentDetectionLogEvent"));
    private static final FieldDescriptor zzaR = a.c(98, FieldDescriptor.builder("onDeviceDocumentCroppingCreateLogEvent"));
    private static final FieldDescriptor zzaS = a.c(99, FieldDescriptor.builder("onDeviceDocumentCroppingLoadLogEvent"));
    private static final FieldDescriptor zzaT = a.c(100, FieldDescriptor.builder("onDeviceDocumentCroppingLogEvent"));
    private static final FieldDescriptor zzaU = a.c(101, FieldDescriptor.builder("aggregatedOnDeviceDocumentCroppingLogEvent"));
    private static final FieldDescriptor zzaV = a.c(102, FieldDescriptor.builder("onDeviceDocumentEnhancementCreateLogEvent"));
    private static final FieldDescriptor zzaW = a.c(103, FieldDescriptor.builder("onDeviceDocumentEnhancementLoadLogEvent"));
    private static final FieldDescriptor zzaX = a.c(104, FieldDescriptor.builder("onDeviceDocumentEnhancementLogEvent"));
    private static final FieldDescriptor zzaY = a.c(105, FieldDescriptor.builder("aggregatedOnDeviceDocumentEnhancementLogEvent"));

    private zzgh() {
    }

    @Override // com.google.firebase.encoders.Encoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, ObjectEncoderContext objectEncoderContext) {
        zzlg zzlgVar = (zzlg) obj;
        ObjectEncoderContext objectEncoderContext2 = objectEncoderContext;
        objectEncoderContext2.add(zzb, zzlgVar.zzf());
        objectEncoderContext2.add(zzc, zzlgVar.zzd());
        objectEncoderContext2.add(zzd, (Object) null);
        objectEncoderContext2.add(zze, (Object) null);
        objectEncoderContext2.add(zzf, zzlgVar.zze());
        objectEncoderContext2.add(zzg, (Object) null);
        objectEncoderContext2.add(zzh, (Object) null);
        objectEncoderContext2.add(zzi, (Object) null);
        objectEncoderContext2.add(zzj, (Object) null);
        objectEncoderContext2.add(zzk, (Object) null);
        objectEncoderContext2.add(zzl, (Object) null);
        objectEncoderContext2.add(zzm, (Object) null);
        objectEncoderContext2.add(zzn, (Object) null);
        objectEncoderContext2.add(zzo, (Object) null);
        objectEncoderContext2.add(zzp, (Object) null);
        objectEncoderContext2.add(zzq, (Object) null);
        objectEncoderContext2.add(zzr, (Object) null);
        objectEncoderContext2.add(zzs, (Object) null);
        objectEncoderContext2.add(zzt, (Object) null);
        objectEncoderContext2.add(zzu, (Object) null);
        objectEncoderContext2.add(zzv, (Object) null);
        objectEncoderContext2.add(zzw, (Object) null);
        objectEncoderContext2.add(zzx, (Object) null);
        objectEncoderContext2.add(zzy, (Object) null);
        objectEncoderContext2.add(zzz, (Object) null);
        objectEncoderContext2.add(zzA, (Object) null);
        objectEncoderContext2.add(zzB, (Object) null);
        objectEncoderContext2.add(zzC, (Object) null);
        objectEncoderContext2.add(zzD, (Object) null);
        objectEncoderContext2.add(zzE, (Object) null);
        objectEncoderContext2.add(zzF, (Object) null);
        objectEncoderContext2.add(zzG, (Object) null);
        objectEncoderContext2.add(zzH, (Object) null);
        objectEncoderContext2.add(zzI, (Object) null);
        objectEncoderContext2.add(zzJ, (Object) null);
        objectEncoderContext2.add(zzK, (Object) null);
        objectEncoderContext2.add(zzL, (Object) null);
        objectEncoderContext2.add(zzM, (Object) null);
        objectEncoderContext2.add(zzN, zzlgVar.zzb());
        objectEncoderContext2.add(zzO, zzlgVar.zza());
        objectEncoderContext2.add(zzP, (Object) null);
        objectEncoderContext2.add(zzQ, (Object) null);
        objectEncoderContext2.add(zzR, (Object) null);
        objectEncoderContext2.add(zzS, (Object) null);
        objectEncoderContext2.add(zzT, (Object) null);
        objectEncoderContext2.add(zzU, (Object) null);
        objectEncoderContext2.add(zzV, (Object) null);
        objectEncoderContext2.add(zzW, (Object) null);
        objectEncoderContext2.add(zzX, (Object) null);
        objectEncoderContext2.add(zzY, (Object) null);
        objectEncoderContext2.add(zzZ, (Object) null);
        objectEncoderContext2.add(zzaa, (Object) null);
        objectEncoderContext2.add(zzab, zzlgVar.zzc());
        objectEncoderContext2.add(zzac, (Object) null);
        objectEncoderContext2.add(zzad, (Object) null);
        objectEncoderContext2.add(zzae, (Object) null);
        objectEncoderContext2.add(zzaf, (Object) null);
        objectEncoderContext2.add(zzag, (Object) null);
        objectEncoderContext2.add(zzah, (Object) null);
        objectEncoderContext2.add(zzai, (Object) null);
        objectEncoderContext2.add(zzaj, (Object) null);
        objectEncoderContext2.add(zzak, (Object) null);
        objectEncoderContext2.add(zzal, (Object) null);
        objectEncoderContext2.add(zzam, (Object) null);
        objectEncoderContext2.add(zzan, (Object) null);
        objectEncoderContext2.add(zzao, (Object) null);
        objectEncoderContext2.add(zzap, (Object) null);
        objectEncoderContext2.add(zzaq, (Object) null);
        objectEncoderContext2.add(zzar, (Object) null);
        objectEncoderContext2.add(zzas, (Object) null);
        objectEncoderContext2.add(zzat, (Object) null);
        objectEncoderContext2.add(zzau, (Object) null);
        objectEncoderContext2.add(zzav, (Object) null);
        objectEncoderContext2.add(zzaw, (Object) null);
        objectEncoderContext2.add(zzax, (Object) null);
        objectEncoderContext2.add(zzay, (Object) null);
        objectEncoderContext2.add(zzaz, (Object) null);
        objectEncoderContext2.add(zzaA, (Object) null);
        objectEncoderContext2.add(zzaB, (Object) null);
        objectEncoderContext2.add(zzaC, (Object) null);
        objectEncoderContext2.add(zzaD, (Object) null);
        objectEncoderContext2.add(zzaE, (Object) null);
        objectEncoderContext2.add(zzaF, (Object) null);
        objectEncoderContext2.add(zzaG, (Object) null);
        objectEncoderContext2.add(zzaH, (Object) null);
        objectEncoderContext2.add(zzaI, (Object) null);
        objectEncoderContext2.add(zzaJ, (Object) null);
        objectEncoderContext2.add(zzaK, (Object) null);
        objectEncoderContext2.add(zzaL, (Object) null);
        objectEncoderContext2.add(zzaM, (Object) null);
        objectEncoderContext2.add(zzaN, (Object) null);
        objectEncoderContext2.add(zzaO, (Object) null);
        objectEncoderContext2.add(zzaP, (Object) null);
        objectEncoderContext2.add(zzaQ, (Object) null);
        objectEncoderContext2.add(zzaR, (Object) null);
        objectEncoderContext2.add(zzaS, (Object) null);
        objectEncoderContext2.add(zzaT, (Object) null);
        objectEncoderContext2.add(zzaU, (Object) null);
        objectEncoderContext2.add(zzaV, (Object) null);
        objectEncoderContext2.add(zzaW, (Object) null);
        objectEncoderContext2.add(zzaX, (Object) null);
        objectEncoderContext2.add(zzaY, (Object) null);
    }
}
